expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy, include
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView
from .apiviews import ExpensesApi
from rest_framework import routers

router = routers.DefaultRouter()
router.register('', ExpensesApi)

urlpatterns = [
    path('api/', include(router.urls)),

    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/edit/',
         UpdateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-edit'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
import datetime

from django import forms
from .models import Expense, Category


class ExpenseSearchForm(forms.ModelForm):
    date_from = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    category_tuple = ((obj.id, obj.name) for obj in Category.objects.all())
    categories = forms.MultipleChoiceField(choices=category_tuple)

    algorithm_choices = [
        ('1', 'sorting by date descending'),
        ('2', 'sorting by date ascending'),
        ('3', 'sorting by category descending'),
        ('4', 'sorting by category ascending')
    ]
    algorithm = forms.CharField(label='Select algorithm', widget=forms.Select(choices=algorithm_choices))

    class Meta:
        model = Expense
        fields = ('name', 'date_from', 'date_to', 'categories')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        self.fields['date_from'].required = False
        self.fields['date_to'].required = False
        self.fields['categories'].required = False
        self.fields['algorithm'].required = False

expenses/views.py
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category, summary_per_date, expenses_per_category
from .pagination_data import form_pagination_data


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            if name:
                queryset = queryset.filter(name__icontains=name)

            date_from = form.cleaned_data.get('date_from')
            date_to = form.cleaned_data.get('date_to')
            if date_from and date_to is None:
                queryset = queryset.filter(date__icontains=date_from)
            if date_to and date_from is None:
                queryset = queryset.filter(date__icontains=date_to)
            if date_from and date_to:
                queryset = queryset.filter(date__range=[date_from, date_to])

            categories = form.cleaned_data.get('categories')
            if categories:
                queryset = queryset.filter(category__in=categories)

            sort = form.cleaned_data.get('algorithm')
            if sort == '1':
                queryset = queryset.order_by('-date')
            if sort == '2':
                queryset = queryset.order_by('date')
            if sort == '3':
                queryset = queryset.order_by('-category')
            if sort == '4':
                queryset = queryset.order_by('category')

        total_amount = sum((obj.amount for obj in queryset))

        return super().get_context_data(
            form=form,
            object_list=queryset,
            form_pagination_data=form_pagination_data(form.cleaned_data),
            total_amount=total_amount,
            summary_per_category=summary_per_category(queryset),
            summary_per_date=summary_per_date(queryset),
            **kwargs)


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        return super().get_context_data(
            object_list=queryset,
            expenses_per_category=expenses_per_category(),
            ** kwargs)

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>expenses</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{obj.name}}
			</td>
			<td>
				{% if obj.name in expenses_per_category.keys %}
					{% for category, counter in expenses_per_category.items %}
						{% if category == obj.name %}
							{{counter}}
						{% endif %}
					{% endfor %}
				{% else %}
					<a>-</a>
				{% endif %}
			</td>
			<td>
				<a href="{% url 'expenses:category-edit' obj.id %}">edit</a>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>
Total amount spent:
  <b>{{ total_amount }}</b>
  <br><br>

<table border="1">
  <caption>Summary per category</caption>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>

<br>
<table border="1">
  <caption>Summary per year</caption>
  <tr>
    {% for date, total in summary_per_date.items %}
	<tr>
		<td>{{date}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="{{ form_pagination_data }}&page=1">&laquo; first</a>
            <a href="{{ form_pagination_data }}&page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="{{ form_pagination_data }}&page={{ page_obj.next_page_number }}">next</a>
            <a href="{{ form_pagination_data }}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}